/serial_driver_node:
  ros__parameters:
    device_name: "/dev/ttyACM0"
    baud_rate: 115200
    flow_control: false
    parity: "none"
    stop_bits: "1"
    chassis_vel_x_scale: -1.0
    chassis_vel_y_scale: -1.0
    chassis_vel_w_scale: 1.0
